<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectionRepository extends EntityRepository
{
    public function findTracked()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Connection c 
                     WHERE c.isTracked = true'
            )
            ->getResult();
    }
}
