<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
    public function findLast()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Course c 
                     ORDER BY c.departureDate ASC'
            )
            ->getFirstResult();
    }
}
